import { jsPDF } from 'jspdf';
import { ReportTemplate } from './types';

export const generatePdf = (template: ReportTemplate, data: any) => {
  const doc = new jsPDF();
  let yPosition = 20;

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(template.name, 20, yPosition);
  yPosition += 15;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 20, yPosition);
  doc.text(`Category: ${template.category}`, 20, yPosition + 5);
  doc.text(`Version: ${template.version}`, 20, yPosition + 10);
  yPosition += 20;

  // Description
  if (template.description) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Report Overview:', 20, yPosition);
    yPosition += 5;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const descriptionLines = doc.splitTextToSize(template.description, 170);
    doc.text(descriptionLines, 20, yPosition);
    yPosition += descriptionLines.length * 5 + 15;
  }

  // Executive Summary Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 20, yPosition);
  yPosition += 10;

  // Generate summary metrics
  const summary = generateSummaryMetrics(data);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  Object.entries(summary).forEach(([category, metrics]) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(`${category}:`, 20, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    Object.entries(metrics as Record<string, any>).forEach(([metric, value]) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      const displayValue = typeof value === 'number' && value >= 1000 ? 
        new Intl.NumberFormat('en-US', { style: 'currency', currency: 'OMR', minimumFractionDigits: 0 }).format(value) :
        String(value);
      doc.text(`  ${metric}: ${displayValue}`, 25, yPosition);
      yPosition += 5;
    });
    yPosition += 5;
  });

  // Detailed Data Sections
  yPosition += 10;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Information', 20, yPosition);
  yPosition += 10;

  // Projects Section
  if (data.projects && data.projects.length > 0) {
    yPosition = addProjectsSection(doc, data.projects, yPosition);
  }

  // Financial Section
  if (data.budgets || data.transactions || data.procurements) {
    yPosition = addFinancialSection(doc, data, yPosition);
  }

  // Resources Section
  if (data.resources && data.resources.length > 0) {
    yPosition = addResourcesSection(doc, data.resources, yPosition);
  }

  // Tasks Section
  if (data.tasks && data.tasks.length > 0) {
    yPosition = addTasksSection(doc, data.tasks, yPosition);
  }

  // Portfolios Section
  if (data.portfolios && data.portfolios.length > 0) {
    yPosition = addPortfoliosSection(doc, data.portfolios, yPosition);
  }

  // Risks Section
  if (data.risks && data.risks.length > 0) {
    yPosition = addRisksSection(doc, data.risks, yPosition);
  } 
  
  // Documents Section
  if (data.documents && data.documents.length > 0) {
    yPosition = addDocumentsSection(doc, data.documents, yPosition);
  }

  // Equipment Site Logs Section
  if (data['equipment-site-logs'] && data['equipment-site-logs'].length > 0) {
    yPosition = addEquipmentSiteLogsSection(doc, data['equipment-site-logs'], yPosition);
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, 20, 280);
    doc.text(`Generated by: ${template.createdBy}`, 120, 280);
    doc.text(`Report: ${template.name}`, 20, 285);
  }

  doc.save(`${template.name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Helper function to generate summary metrics
const generateSummaryMetrics = (data: any) => {
  const summary: any = {};

  // Projects Summary
  if (data.projects) {
    const projects = Array.isArray(data.projects) ? data.projects : [];
    summary['Projects'] = {
      'Total Projects': projects.length,
      'Active Projects': projects.filter((p: any) => p.status === 'active' || p.status === 'execution').length,
      'Completed Projects': projects.filter((p: any) => p.status === 'completed').length
    };
  }

  // Financial Summary
  if (data.budgets || data.transactions || data.procurements) {
    const budgets = data.budgets || [];
    const transactions = data.transactions || [];
    const procurements = data.procurements || [];
    
    const totalBudget = budgets.reduce((sum: number, budget: any) => sum + (budget.planned_amount || 0), 0);
    const totalSpent = budgets.reduce((sum: number, budget: any) => sum + (budget.actual_amount || 0), 0) +
                      transactions.reduce((sum: number, transaction: any) => sum + (transaction.amount || 0), 0) +
                      procurements.reduce((sum: number, procurement: any) => sum + (procurement.actual_cost || 0), 0);
    
    summary['Financial'] = {
      'Total Budget': totalBudget,
      'Total Spent': totalSpent,
      'Remaining Budget': totalBudget - totalSpent
    };
  }

  // Resources Summary
  if (data.resources) {
    const resources = Array.isArray(data.resources) ? data.resources : [];
    summary['Resources'] = {
      'Total Resources': resources.length,
      'Available Resources': resources.filter((r: any) => !r.assignments || r.assignments.length === 0).length,
      'Allocated Resources': resources.filter((r: any) => r.assignments && r.assignments.length > 0).length
    };
  }

  // Tasks Summary
  if (data.tasks) {
    const tasks = Array.isArray(data.tasks) ? data.tasks : [];
    summary['Tasks'] = {
      'Total Tasks': tasks.length,
      'Completed Tasks': tasks.filter((t: any) => t.status === 'completed').length,
      'In Progress Tasks': tasks.filter((t: any) => t.status === 'in_progress' || t.status === 'active').length,
      'On Hold Tasks': tasks.filter((t: any) => t.status === 'on_hold').length
    };
  }

  // Documents Summary
  if (data.documents) {
    const documents = Array.isArray(data.documents) ? data.documents : [];
    summary['Documents'] = {
      'Total Documents': documents.length,
      'Active Documents': documents.filter((d: any) => d.status === 'active' || d.status === 'approved').length,
      'Pending Review': documents.filter((d: any) => d.status === 'pending' || d.status === 'review').length
    };
  }

  // Equipment Site Logs Summary
  if (data['equipment-site-logs']) {
    const equipmentLogs = Array.isArray(data['equipment-site-logs']) ? data['equipment-site-logs'] : [];
    summary['Equipment'] = {
      'Total Equipment Logs': equipmentLogs.length,
      'Active Equipment': equipmentLogs.filter((log: any) => !log.logged_out_date).length,
      'Completed Assignments': equipmentLogs.filter((log: any) => log.logged_out_date).length
    };
  }

  return summary;
};

// Helper function to add projects section
const addProjectsSection = (doc: jsPDF, projects: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Projects', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  projects.forEach((project: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(project.name || project.project_name || 'Unnamed Project', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Status: ${project.status || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    
    if (project.progress_percentage !== undefined) {
      doc.text(`Progress: ${project.progress_percentage}%`, 25, yPosition);
      yPosition += 4;
    }
    
    if (project.start_date) {
      doc.text(`Start Date: ${new Date(project.start_date).toLocaleDateString()}`, 25, yPosition);
      yPosition += 4;
    }
    
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add financial section
const addFinancialSection = (doc: jsPDF, data: any, startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Overview', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const budgets = data.budgets || [];
  const transactions = data.transactions || [];
  const procurements = data.procurements || [];

  // Budget Summary
  if (budgets.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Budget Summary:', 20, yPosition);
    yPosition += 4;
    doc.setFont('helvetica', 'normal');

    const totalPlanned = budgets.reduce((sum: number, budget: any) => sum + (budget.planned_amount || 0), 0);
    const totalActual = budgets.reduce((sum: number, budget: any) => sum + (budget.actual_amount || 0), 0);
    
    doc.text(`Total Planned Budget: OMR ${totalPlanned.toLocaleString()}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Total Actual Spent: OMR ${totalActual.toLocaleString()}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Variance: OMR ${(totalPlanned - totalActual).toLocaleString()}`, 25, yPosition);
    yPosition += 6;
  }

  // Recent Transactions
  if (transactions.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Recent Transactions:', 20, yPosition);
    yPosition += 4;
    doc.setFont('helvetica', 'normal');

    transactions.slice(0, 5).forEach((transaction: any) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`OMR ${transaction.amount?.toLocaleString()} - ${transaction.description || transaction.category || 'Transaction'}`, 25, yPosition);
      yPosition += 4;
    });
    yPosition += 3;
  }

  return yPosition;
};

// Helper function to add resources section
const addResourcesSection = (doc: jsPDF, resources: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Resources', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  resources.forEach((resource: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(resource.name || resource.resource_name || 'Unnamed Resource', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Type: ${resource.type || resource.resource_type || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    
    doc.text(`Status: ${resource.status || resource.availability_status || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add tasks section
const addTasksSection = (doc: jsPDF, tasks: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tasks', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  tasks.forEach((task: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(task.name || task.task_name || 'Unnamed Task', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Status: ${task.status || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    
    if (task.priority) {
      doc.text(`Priority: ${task.priority}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (task.start_date) {
      doc.text(`Start Date: ${new Date(task.start_date).toLocaleDateString()}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (task.end_date) {
      doc.text(`End Date: ${task.end_date ? new Date(task.end_date).toLocaleDateString() : 'N/A'}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (task.progress_percentage !== undefined) {
      doc.text(`Progress: ${task.progress_percentage}%`, 25, yPosition);
      yPosition += 4;
    }
    
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add portfolios section
const addPortfoliosSection = (doc: jsPDF, portfolios: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Portfolios', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  portfolios.forEach((portfolio: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(portfolio.name || portfolio.portfolio_name || 'Unnamed Portfolio', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Status: ${portfolio.status || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    
    if (portfolio.projects) {
      doc.text(`Projects: ${portfolio.projects.length}`, 25, yPosition);
      yPosition += 4;
    }
    
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add risks section
const addRisksSection = (doc: jsPDF, risks: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Risks', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  risks.forEach((risk: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(risk.name || risk.title || 'Unnamed Risk', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Impact: ${risk.impact || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Probability: ${risk.probability || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Status: ${risk.status || 'N/A'}`, 25, yPosition);
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add documents section
const addDocumentsSection = (doc: jsPDF, documents: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Documents', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  documents.forEach((document: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(document.name || document.title || 'Unnamed Document', 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Type: ${document.type || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Status: ${document.status || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    doc.text(`Version: ${document.version || 'N/A'}`, 25, yPosition);
    yPosition += 4;
    if (document.upload_date) {
      doc.text(`Upload Date: ${new Date(document.upload_date).toLocaleDateString()}`, 25, yPosition);
      yPosition += 4;
    }
    yPosition += 3;
  });

  return yPosition;
};

// Helper function to add equipment site logs section
const addEquipmentSiteLogsSection = (doc: jsPDF, equipmentLogs: any[], startY: number): number => {
  let yPosition = startY;
  
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Equipment Site Logs', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  equipmentLogs.forEach((log: any) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    const resourceName = log.resource?.name || log.resource?.resource_name || 'Unknown Equipment';
    doc.text(resourceName, 20, yPosition);
    yPosition += 4;
    
    doc.setFont('helvetica', 'normal');
    const siteName = log.site?.name || log.site?.site_name || 'Unknown Site';
    doc.text(`Site: ${siteName}`, 25, yPosition);
    yPosition += 4;
    
    if (log.logged_in_date) {
      doc.text(`Logged In: ${new Date(log.logged_in_date).toLocaleDateString()}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (log.logged_out_date) {
      doc.text(`Logged Out: ${new Date(log.logged_out_date).toLocaleDateString()}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (log.usage_hours) {
      doc.text(`Usage Hours: ${log.usage_hours}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (log.condition_before) {
      doc.text(`Condition Before: ${log.condition_before}`, 25, yPosition);
      yPosition += 4;
    }
    
    if (log.condition_after) {
      doc.text(`Condition After: ${log.condition_after}`, 25, yPosition);
      yPosition += 4;
    }
    
    yPosition += 3;
  });

  return yPosition;
};