// This file must only be imported server-side (API routes or server actions). Never import in client or shared code.
import PptxGenJS from 'pptxgenjs';
import { ReportTemplate } from './types';

export function generatePptx(template: ReportTemplate, data: any) {
  const pptx = new PptxGenJS();

  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = template.createdBy;
  pptx.company = 'Project Management System';
  pptx.subject = template.name;
  pptx.title = template.name;

  // Helper function to clean data by removing primary key IDs but keeping foreign keys
  const cleanDataForExport = (items: any[]) => {
    return items.map(item => {
      const cleaned: any = {};
      Object.entries(item).forEach(([key, value]) => {
        // Remove primary keys (like id, project_id, user_id, task_id, resource_id, budget_id, risk_id, portfolio_id, wbs_id, document_id)
        if (key === 'id' || key === 'project_id' || key === 'user_id' || key === 'task_id' || 
            key === 'resource_id' || key === 'budget_id' || key === 'risk_id' || 
            key === 'portfolio_id' || key === 'wbs_id' || key === 'document_id') {
          return; // Skip primary keys
        }
        
        // Keep foreign keys and other data
        cleaned[key] = value;
      });
      return cleaned;
    });
  };

  // Helper function to format field names
  const formatFieldName = (fieldName: string) => {
    return fieldName
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .replace(/_/g, ' ');
  };

  // Helper function to create summary metrics
  const createSummaryMetrics = (data: any) => {
    const summary: any = {};

    // Projects Summary
    if (data.projects) {
      const projects = Array.isArray(data.projects) ? data.projects : [];
      summary['Projects'] = {
        'Total Projects': projects.length,
        'Active Projects': projects.filter((p: any) => p.status === 'active' || p.status === 'execution').length,
        'Completed Projects': projects.filter((p: any) => p.status === 'completed').length
      };
    }

    // Financial Summary
    if (data.budgets || data.transactions || data.procurements) {
      const budgets = data.budgets || [];
      const transactions = data.transactions || [];
      const procurements = data.procurements || [];
      
      const totalBudget = budgets.reduce((sum: number, budget: any) => sum + (budget.planned_amount || 0), 0);
      const totalSpent = budgets.reduce((sum: number, budget: any) => sum + (budget.actual_amount || 0), 0) +
                        transactions.reduce((sum: number, transaction: any) => sum + (transaction.amount || 0), 0) +
                        procurements.reduce((sum: number, procurement: any) => sum + (procurement.actual_cost || 0), 0);
      
      summary['Financial'] = {
        'Total Budget': totalBudget,
        'Total Spent': totalSpent,
        'Remaining Budget': totalBudget - totalSpent
      };
    }

    // Resources Summary
    if (data.resources) {
      const resources = Array.isArray(data.resources) ? data.resources : [];
      summary['Resources'] = {
        'Total Resources': resources.length,
        'Available Resources': resources.filter((r: any) => !r.assignments || r.assignments.length === 0).length,
        'Allocated Resources': resources.filter((r: any) => r.assignments && r.assignments.length > 0).length
      };
    }

    // Tasks Summary
    if (data.tasks) {
      const tasks = Array.isArray(data.tasks) ? data.tasks : [];
      summary['Tasks'] = {
        'Total Tasks': tasks.length,
        'Completed Tasks': tasks.filter((t: any) => t.status === 'completed').length,
        'In Progress Tasks': tasks.filter((t: any) => t.status === 'in_progress' || t.status === 'active').length
      };
    }

    return summary;
  };

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText(template.name, { 
    x: 0.5, 
    y: 1.5, 
    fontSize: 28, 
    bold: true, 
    color: '363636',
    align: 'center',
    w: '90%'
  });

  titleSlide.addText(template.description || '', {
    x: 0.5,
    y: 2.5,
    fontSize: 14,
    color: '7F7F7F',
    align: 'center',
    w: '90%'
  });

  titleSlide.addText(`Generated by: ${template.createdBy} on ${new Date().toLocaleDateString()}`, {
    x: 0.5,
    y: 3.5,
    fontSize: 12,
    color: '7F7F7F',
    align: 'center',
    w: '90%'
  });

  // Executive Summary slide
  const summarySlide = pptx.addSlide();
  summarySlide.addText('Executive Summary', { 
    x: 0.5, 
    y: 0.25, 
    fontSize: 24, 
    bold: true, 
    color: '363636' 
  });

  const summary = createSummaryMetrics(data);
  let summaryY = 1.0;
  
  Object.entries(summary).forEach(([category, metrics]) => {
    summarySlide.addText(category, { 
      x: 0.5, 
      y: summaryY, 
      fontSize: 16, 
      bold: true, 
      color: '363636' 
    });
    summaryY += 0.3;

    Object.entries(metrics as Record<string, any>).forEach(([metric, value]) => {
      const displayValue = typeof value === 'number' && value >= 1000 ? 
        new Intl.NumberFormat('en-US', { style: 'currency', currency: 'OMR', minimumFractionDigits: 0 }).format(value) :
        String(value);
      
      summarySlide.addText(`• ${metric}: ${displayValue}`, { 
        x: 0.7, 
        y: summaryY, 
        fontSize: 12, 
        color: '363636' 
      });
      summaryY += 0.2;
    });
    summaryY += 0.2;
  });

  // Helper function to distribute data across multiple slides
  const createDataSlides = (title: string, data: any[], maxRowsPerSlide: number = 8) => {
    if (!data || data.length === 0) return;

    const cleanedData = cleanDataForExport(data);
    const headers = Object.keys(cleanedData[0] || {});
    const formattedHeaders = headers.map(formatFieldName);

    // Calculate how many slides we need
    const totalSlides = Math.ceil(cleanedData.length / maxRowsPerSlide);

    for (let slideIndex = 0; slideIndex < totalSlides; slideIndex++) {
      const slide = pptx.addSlide();
      const slideTitle = totalSlides > 1 ? `${title} (Page ${slideIndex + 1} of ${totalSlides})` : title;
      
      slide.addText(slideTitle, { 
        x: 0.5, 
        y: 0.25, 
        fontSize: 20, 
        bold: true, 
        color: '363636' 
      });

      // Get data for this slide
      const startIndex = slideIndex * maxRowsPerSlide;
      const endIndex = Math.min(startIndex + maxRowsPerSlide, cleanedData.length);
      const slideData = cleanedData.slice(startIndex, endIndex);

      // Create table data
      const tableData = [formattedHeaders];
      
      slideData.forEach((item: any) => {
        const row = headers.map(header => {
          const value = item[header];
          if (typeof value === 'object' && value !== null) {
            return JSON.stringify(value).substring(0, 30);
          }
          return String(value || '').substring(0, 30);
        });
        tableData.push(row);
      });

      slide.addTable(tableData as any, {
        x: 0.5,
        y: 1.0,
        w: '90%',
        h: '70%',
        border: { type: 'solid', pt: 1, color: 'CCCCCC' },
        fill: { color: 'F1F1F1' },
        color: '363636',
        fontSize: 10,
        align: 'left'
      });
    }
  };

  // Create slides for each data type
  if (data.projects && data.projects.length > 0) {
    createDataSlides('Projects Overview', data.projects, 6);
  }

  if (data.budgets && data.budgets.length > 0) {
    createDataSlides('Budget Information', data.budgets, 8);
  }

  if (data.transactions && data.transactions.length > 0) {
    createDataSlides('Financial Transactions', data.transactions, 8);
  }

  if (data.resources && data.resources.length > 0) {
    createDataSlides('Resources', data.resources, 6);
  }

  if (data.tasks && data.tasks.length > 0) {
    createDataSlides('Tasks', data.tasks, 8);
  }

  if (data.portfolios && data.portfolios.length > 0) {
    createDataSlides('Portfolios', data.portfolios, 6);
  }

  if (data.risks && data.risks.length > 0) {
    createDataSlides('Risks', data.risks, 6);
  }

  // Financial Overview slide
  if (data.budgets || data.transactions || data.procurements) {
    const financialSlide = pptx.addSlide();
    financialSlide.addText('Financial Overview', { 
      x: 0.5, 
      y: 0.25, 
      fontSize: 20, 
      bold: true, 
      color: '363636' 
    });

    const budgets = data.budgets || [];
    const transactions = data.transactions || [];
    const procurements = data.procurements || [];

    let financialY = 1.0;

    // Budget Summary
    if (budgets.length > 0) {
      financialSlide.addText('Budget Summary:', { 
        x: 0.5, 
        y: financialY, 
        fontSize: 14, 
        bold: true, 
        color: '363636' 
      });
      financialY += 0.3;

      const totalPlanned = budgets.reduce((sum: number, budget: any) => sum + (budget.planned_amount || 0), 0);
      const totalActual = budgets.reduce((sum: number, budget: any) => sum + (budget.actual_amount || 0), 0);
      
      financialSlide.addText(`Total Planned Budget: OMR ${totalPlanned.toLocaleString()}`, { 
        x: 0.7, 
        y: financialY, 
        fontSize: 12, 
        color: '363636' 
      });
      financialY += 0.2;
      
      financialSlide.addText(`Total Actual Spent: OMR ${totalActual.toLocaleString()}`, { 
        x: 0.7, 
        y: financialY, 
        fontSize: 12, 
        color: '363636' 
      });
      financialY += 0.2;
      
      financialSlide.addText(`Variance: OMR ${(totalPlanned - totalActual).toLocaleString()}`, { 
        x: 0.7, 
        y: financialY, 
        fontSize: 12, 
        color: '363636' 
      });
      financialY += 0.4;
    }

    // Recent Transactions
    if (transactions.length > 0) {
      financialSlide.addText('Recent Transactions:', { 
        x: 0.5, 
        y: financialY, 
        fontSize: 14, 
        bold: true, 
        color: '363636' 
      });
      financialY += 0.3;

      transactions.slice(0, 5).forEach((transaction: any) => {
        financialSlide.addText(`OMR ${transaction.amount?.toLocaleString()} - ${transaction.description || transaction.category || 'Transaction'}`, { 
          x: 0.7, 
          y: financialY, 
          fontSize: 12, 
          color: '363636' 
        });
        financialY += 0.2;
      });
    }
  }

  // Conclusion slide
  const conclusionSlide = pptx.addSlide();
  conclusionSlide.addText('Report Generated Successfully', { 
    x: 0.5, 
    y: 1.5, 
    fontSize: 24, 
    bold: true, 
    color: '363636',
    align: 'center',
    w: '90%'
  });

  conclusionSlide.addText('All data has been processed and organized', { 
    x: 0.5, 
    y: 2.5, 
    fontSize: 14, 
    color: '7F7F7F',
    align: 'center',
    w: '90%'
  });

  conclusionSlide.addText(`Generated on: ${new Date().toLocaleString()}`, { 
    x: 0.5, 
    y: 3.0, 
    fontSize: 12, 
    color: '7F7F7F',
    align: 'center',
    w: '90%'
  });

  pptx.writeFile({ fileName: `${template.name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pptx` });

  return pptx;
} 